/*  Message-number definitions derived from "ELWALC2C.MSG"  */

#define ALCATR      1
#define YOUWIN      3
#define WINKSO      4
#define WINKSU      5
#define BECMSD      6
#define BECMSA      7
#define IMSAMN      8
#define IMSYOU      9
#define IMSGEN     10
#define ITSMSN     11
#define ITSMSD     12
#define WHOMS0     13
#define TRUQUE     14
#define NOQUES     15
#define RDNM00     16
#define RDNM01     17
#define RDNM02     18
#define RDNM03     19
#define RDNM04     20
